import esbuild from "esbuild";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

try {
  const result = await esbuild.build({
    banner: { js: banner },
    entryPoints: ["src/main.ts", "src/ui/styles/styles.scss"],
    entryNames: "[name]",
    outdir: ".",
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: false,
    treeShaking: true,
    define: { "process.env.NODE_ENV": '"production"' },
    minify: false,
    plugins: [
      sassPlugin({ type: "css", outputStyle: "compressed" }),
    ],
  });
  console.log("✅ Build completed successfully!");
} catch (error) {
  console.error("❌ Build failed:", error);
  process.exit(1);
}
